import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans - Yes, there is a difference in the data types of the variables 'list_' and 'array_list'. In the given code, 'list_' is a Python list containing string elements, while 'array_list' is a NumPy array created from that list. The data types of the elements in 'list_' are Python strings, while the data type of the elements in 'array_list' will be determined by NumPy based on the input data.

You can print the data types of both variables using the following code:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)


Data type of list_: <class 'str'>
Data type of array_list: <U1


In this code, 'type(list_[0])' gives you the data type of the individual element in the Python list, and 'array_list.dtype' gives you the data type of the elements in the NumPy array.

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data types in list_:")
for element in list_:
    print(type(element))

print("\nData types in array_list:")
for element in array_list:
    print(element.dtype)


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<U1
<U1
<U1
<U1
<U1


This code iterates through each element in 'list_' and prints its data type using 'type(element)'. For the 'array_list', it iterates through each element and prints the data type using 'element.dtype'. Note that for the 'array_list', the data types will be inferred by NumPy during array creation based on the input data.

Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.



Ans - Yes, there will be a difference in the data type of the elements present in the variables 'list_' and 'array_list' after using 'array_list = np.array(object=list_, dtype=int)'. The 'dtype=int' argument specifies that the elements in the resulting NumPy array 'array_list' should be converted to integers.

Here's the corrected version of the code to print the data types of each element in both the variables 'list_' and 'array_list':

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types in list_:")
for element in list_:
    print(type(element))

print("\nData types in array_list:")
for element in array_list:
    print(type(element))


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In this code, for 'list_', the data types of elements will still be strings ('1', '2', etc.), whereas for 'array_list', the data types of elements will be integers (1, 2, etc.).

Consider the below code to answer further questions:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

Ans - Certainly! Here's the code to find the shape and size of the NumPy array 'num_array':

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape
print("Shape of num_array:", num_array.shape)

# (ii) Size
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In this code, 'num_array.shape' will give you a tuple representing the dimensions of the array, and 'num_array.size' will give you the total number of elements in the array.

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

Ans - Certainly! You can create a NumPy array of a 3x3 matrix containing zeros using the 'numpy.zeros' function. Here's the code to achieve that:

In [5]:
import numpy as np

# Create a 3x3 array of zeros
zero_array = np.zeros((3, 3))

print("Array of zeros:")
print(zero_array)


Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Ans - Sure! You can create an identity matrix of shape (5, 5) using the 'numpy.identity' function. Here's how you can do it:

In [6]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

print("Identity matrix:")
print(identity_matrix)


Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
